// import Providers from '@/provider'
import './globals.css'
import { Inter } from 'next/font/google'
// import AuthContextProvider from '@/provider/AuthContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'login Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body className={inter.className}>{children}</body>
   
     
    </html>
  )
}
