// import Providers from '@/provider'
import './globals.css'
import { Inter } from 'next/font/google'
// import AuthContextProvider from '@/provider/AuthContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Providers> */}
      {/* <AuthContextProvider> */}
      <body className={inter.className}>{children}</body>
      {/* </AuthContextProvider> */}
      {/* </Providers> */}
     
    </html>
  )
}
